### PR TITLE
Create test

### PR DESCRIPTION
**Pull request by e-coders**

### CODE REVIEW

**Comment by e-coders** [comment]
@all-contributors add @e-coders for docs, ideas, website

**Comment by e-coders** [comment]
@all-contributors add @ItziSpyder for coding, owner, docs, ideas, bug fixes

**Comment by e-coders** [comment]
@all-contributors add @TheTrouper for website, coding, owner, fixes

**Comment by e-coders** [comment]
@all-contributors add @ayaanibrahimtutla for website, ideas

**Comment by thetrouper** [comment]
Y'all are blowing up my personal email right now, can you please get in contact using discord, instead of chatting through a GitHub pill request.

**Comment by e-coders** [comment]
@all-contributors add @I-no-one for coding, bugs, ideas

**Comment by e-coders** [comment]
> Y'all are blowing up my personal email right now, can you please get in contact using discord, instead of chatting through a GitHub pull request.

Frrr

**Comment by e-coders** [comment]
it was only made to add contributor.

**Pull request closed without merging**
